// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use Vite environment variables with fallbacks for backwards compatibility
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kssuxhxqhbwicyguzoik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzc3V4aHhxaGJ3aWN5Z3V6b2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzA1NTIsImV4cCI6MjA2ODYwNjU1Mn0.gnjnVhMslf1dILZNmXlH0RrMjnlfSBmFENfPcDcptcs";

// Validate that we have the required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing required Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
